/*
 * Teleport
 * Copyright (C) 2026  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package teleport.desktopcontrol.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/gravitational/teleport/api/gen/proto/go/teleport/desktop_control/v1;deskctopcontrolv1";

message GetCertificateAndKeyRequest {}

// TLS certificate and private key used for authentication with the Windows Desktop Service.
message GetCertificateAndKeyResponse {
  bytes cert = 1;
  bytes key = 2;
}

// Metadata for an RDP license.
message LicenseMetadata {
  uint32 version = 1;
  string issuer = 2;
  string company = 3;
  string product_id = 4;
}

message ReadRdpLicenseRequest {
  LicenseMetadata license_metadata = 1;
}

// Response message for ReadRdpLicense RPC. Contains the cached RDP license information if it exists.
message ReadRdpLicenseResponse {
  google.protobuf.BytesValue license_info = 1;
}

// Represents an RDP license.
message License {
  LicenseMetadata metadata = 1;
  bytes license_info = 2;
}

message WriteRdpLicenseRequest {
  License license = 1;
}

message WriteRdpLicenseResponse {}

message ControlRequest {
  oneof request {
    GetCertificateAndKeyRequest get_certificate_and_key_request = 1;
    ReadRdpLicenseRequest read_rdp_license_request = 2;
    WriteRdpLicenseRequest write_rdp_license_request = 3;
  }
}

message ControlResponse {
  oneof response {
    GetCertificateAndKeyResponse get_certificate_and_key_response = 1;
    ReadRdpLicenseResponse read_rdp_license_response = 2;
    WriteRdpLicenseResponse write_rdp_license_response = 3;
  }
}
